import * as password from '../../core/utils/password.js'

import type UserRepository from './user.repository.js'

import type { TeacherCreateInput } from './user.schema.js'
import type { User, NewUser, Teacher, NewTeacher } from '../../db/types.js'

export default class UserService {

  constructor(private readonly userRepository: UserRepository) { }

  async createTeacher (teacher: TeacherCreateInput): Promise<User & Teacher> {

    const hashedPassword = await password.hash(teacher.password)
    teacher.passwordHash = hashedPassword

    const fullUserDetails: NewUser = {
      fullName: teacher.fullName,
      personalEmail: teacher.personalEmail,
      phone: teacher.phone,
      passwordHash: teacher.passwordHash,

      gender: teacher.gender,
      profilePictureUrl: teacher.profilePictureUrl ?? null,
      bio: teacher.bio ?? null,
    }

    // teacherId will be generated by db when userDetails are inserted
    const partialTeacherDetails: Omit<NewTeacher, 'teacherId'> = {
      designation: teacher.designation,
      departmentId: teacher.departmentId,
    }

    return await this.userRepository.createTeacher(fullUserDetails, partialTeacherDetails)
  }

}